# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast but sloppy HTML rendering
#'
#' Renders \pkg{htmltools} tag graphs into HTML. This is missing several
#' features of \link[htmltools]{renderTags}, including but not necessarily
#' limited to: singleton, head, and dependency handling; converting objects
#' to tags using \link[htmltools]{as.tags}; combining attributes with the
#' same name by space-delimiting them; and possibly others.
#'
#' @param x An htmltools tag object.
#' @param indent Initial indent level. Use a negative value for no indentation.
#' @return An HTML string (marked as if returned from \link[htmltools]{HTML}).
#' @useDynLib fasttags
#' @importFrom Rcpp evalCpp
#' @export
fastrender <- function(x, indent = 0L) {
    .Call('fasttags_fastrender', PACKAGE = 'fasttags', x, indent)
}

